{% extends "layout.phtml" %}

{% block title %}
Calendar
{% endblock %}

{% block page_title %}
Upcoming Events
{% endblock %}

{% block content %}
<div class="container-fluid">
    <!-- Individual events -->
    <div class="row">
        <h3>Test Event</h3>
        <h4>June 24th, 7pm, 1070 DOW</h4>
        <p>This is a test event with test text.</p>
    </div>
    <div class="row">
        <h3>Test Event</h3>
        <h4>June 24th, 7pm, 1070 DOW</h4>
        <p>This is a test event with test text.</p>
    </div>
</div>
{% endblock %}
