{% extends "layout.phtml" %}

{% block title %}
Calendar
{% endblock %}

{% block page_title %}
Upcoming Events
{% endblock %}

{% block content %}
<div class="container-fluid">
   <iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=200&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=torus%40umich.edu&amp;color=%23875509&amp;ctz=America%2FNew_York" style=" border-width:0 " width="1080" height="200" frameborder="0" scrolling="no"></iframe>
    <!-- Individual events -->
    <div class="row">
        <h3>Test Event</h3>
        <h4>June 24th, 7pm, 1070 DOW</h4>
        <p>This is a test event with test text.</p>
    </div>
    <div class="row">
        <h3>Test Event</h3>
        <h4>June 24th, 7pm, 1070 DOW</h4>
        <p>This is a test event with test text.</p>
    </div>
</div>
{% endblock %}
