{% extends "layout.phtml" %}

{% block title %}
{{event.name}} - Event Logger
{% endblock %}

{% block page_title %}
{{event.name}}
{% endblock %}

{% block content %}
        <!-- Form for  registering for event-->
       <form role="form" name="input" id="event_form" action="{{ROOTPATH}}/views/event_logger_post.php" method="post">
        <input type="hidden" name="event" value="{{event.objectId}}">
        <div class="form-group">
          <label for="uniqname">Uniqname:</label>
        <input id="uniqname" type="text" autofocus id="clear" name="uniqname">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
       </form>

       <script type="text/javascript">
        // this is the id of the form
        $(function() {
          $("").focus();
        });
       </script>
{% endblock %}
