{% extends "layout.phtml" %}

{% block title %}
{{event.name}} - Event Logger
{% endblock %}

{% block content %}
        <h1> {{event.name}} </h1>
        <!-- Form for  registering for event-->
       <form name="input" id="event_form" action="{{ROOTPATH}}/views/event_logger_post.php" method="post">
        <input type="hidden" name="event" value="{{event.objectId}}">
        Uniqname: <input type="text" autofocus id="clear" name="uniqname">
        <input type="submit" value="Submit">
       </form>

       <script type="text/javascript">
        // this is the id of the form
        $(function() {
          $("").focus();
        });
       </script>
{% endblock %}
