{% extends "layout.phtml" %}

{% block title %}
CSE Scholars
{% endblock %}

{% block page_title %}
University of Michigan
{% endblock %}

{% block content %}
<!-- Carousel or main image or whatever -->
<div class="container_top container-fluid" id="index_container">
    <div class="row asset_top">

<!-- BEGINNING OF SLIDER -->
        <div id="wowslider-container1">
        <div class="ws_images"><ul>
            <li><img src="data1/images/p1000016.jpg" alt="P1000016" title="P1000016" id="wows1_0"/></li>
            <li><img src="data1/images/p1000017.jpg" alt="P1000017" title="P1000017" id="wows1_1"/></li>
            <li><img src="data1/images/p1000018.jpg" alt="P1000018" title="P1000018" id="wows1_2"/></li>
            <li><img src="data1/images/p1000019.jpg" alt="P1000019" title="P1000019" id="wows1_3"/></li>
            <li><img src="data1/images/p1000020.jpg" alt="P1000020" title="P1000020" id="wows1_4"/></li>
            <li><img src="data1/images/p1000021.jpg" alt="P1000021" title="P1000021" id="wows1_5"/></li>
            <li><img src="data1/images/p1000022.jpg" alt="P1000022" title="P1000022" id="wows1_6"/></li>
            <li><img src="data1/images/p1000023.jpg" alt="P1000023" title="P1000023" id="wows1_7"/></li>
            <li><img src="data1/images/p1000024.jpg" alt="P1000024" title="P1000024" id="wows1_8"/></li>
            <li><img src="data1/images/p1000025.jpg" alt="P1000025" title="P1000025" id="wows1_9"/></li>
            <li><img src="data1/images/p1000026.jpg" alt="P1000026" title="P1000026" id="wows1_10"/></li>
            
    </ul></div>
<span class="wsl"><a href="http://wowslider.com/vs">jquery slideshow</a> by WOWSlider.com v7.4m</span>

    <script type="text/javascript" src="engine1/wowslider.js"></script>
    <script type="text/javascript" src="engine1/script.js"></script>
<!-- END OF SLIDER -->


    </div>
</div>
<!-- End the thing -->

<!-- 3 Blocks -->
<div class="container-fluid" id="index_container">
    <div class="row">
        <div class="col-lg-4">
            <div class="asset_box"></div>
            <h2 class="text-center">Corporate</h2>
            <p> All the texts and I'm typing and words and this needs to be really long. And pop culture references. Meta! Meta! Companies. Yelp is Cool. So is Microsoft and Amazon. One of who Yelp makes an app for and one of who makes an app for Yelp. Guesses anyone?</p>
        </div>

        <div class="col-lg-4">
            <div class="asset_box">

                <!-- begin of middle slider -->
                    <div id="wowslider-container2">
    <div class="ws_images"><ul>
        <li><img src="data2/images/p1000192.jpg" alt="P1000192" title="P1000192" id="wows2_0"/></li>
        <li><img src="data2/images/p1000193.jpg" alt="P1000193" title="P1000193" id="wows2_1"/></li>
        <li><img src="data2/images/p1000194.jpg" alt="P1000194" title="P1000194" id="wows2_2"/></li>
        <li><img src="data2/images/p1000195.jpg" alt="P1000195" title="P1000195" id="wows2_3"/></li>
        <li><img src="data2/images/p1000196.jpg" alt="P1000196" title="P1000196" id="wows2_4"/></li>
        <li><img src="data2/images/p1000197.jpg" alt="P1000197" title="P1000197" id="wows2_5"/></li>
        <li><img src="data2/images/p1000198.jpg" alt="P1000198" title="P1000198" id="wows2_6"/></li>
        <li><img src="data2/images/p1000199.jpg" alt="P1000199" title="P1000199" id="wows2_7"/></li>
        <li><img src="data2/images/p1000200.jpg" alt="P1000200" title="P1000200" id="wows2_8"/></li>
        <li><img src="data2/images/p1000201.jpg" alt="P1000201" title="P1000201" id="wows2_9"/></li>
        <li><img src="data2/images/p1000202.jpg" alt="P1000202" title="P1000202" id="wows2_10"/></li>
        <li><img src="data2/images/p1000203.jpg" alt="P1000203" title="P1000203" id="wows2_11"/></li>
        <li><img src="data2/images/p1000204.jpg" alt="P1000204" title="P1000204" id="wows2_12"/></li>
        <li><img src="data2/images/p1000205.jpg" alt="P1000205" title="P1000205" id="wows2_13"/></li>
        <li><img src="data2/images/p1000206.jpg" alt="P1000206" title="P1000206" id="wows2_14"/></li>
        <li><img src="data2/images/p1000207.jpg" alt="P1000207" title="P1000207" id="wows2_15"/></li>
        <li><img src="data2/images/p1000208.jpg" alt="P1000208" title="P1000208" id="wows2_16"/></li>
        <li><img src="data2/images/p1000209.jpg" alt="P1000209" title="P1000209" id="wows2_17"/></li>
        <li><img src="data2/images/p1000210.jpg" alt="P1000210" title="P1000210" id="wows2_18"/></li>
        <li><img src="data2/images/p1000211.jpg" alt="P1000211" title="P1000211" id="wows2_19"/></li>
        <li><img src="data2/images/p1000212.jpg" alt="P1000212" title="P1000212" id="wows2_20"/></li>
        <li><img src="data2/images/p1000213.jpg" alt="P1000213" title="P1000213" id="wows2_21"/></li>
        <li><img src="data2/images/p1000214.jpg" alt="P1000214" title="P1000214" id="wows2_22"/></li>
        <li><img src="data2/images/p1000215.jpg" alt="P1000215" title="P1000215" id="wows2_23"/></li>
        <li><img src="data2/images/p1000216.jpg" alt="P1000216" title="P1000216" id="wows2_24"/></li>
        <li><img src="data2/images/p1000217.jpg" alt="P1000217" title="P1000217" id="wows2_25"/></li>
        <li><img src="data2/images/p1000218.jpg" alt="P1000218" title="P1000218" id="wows2_26"/></li>
        <li><img src="data2/images/p1000219.jpg" alt="P1000219" title="P1000219" id="wows2_27"/></li>
        <li><img src="data2/images/p1000220.jpg" alt="P1000220" title="P1000220" id="wows2_28"/></li>
        <li><img src="data2/images/p1000221.jpg" alt="P1000221" title="P1000221" id="wows2_29"/></li>
        <li><img src="data2/images/p1000222.jpg" alt="P1000222" title="P1000222" id="wows2_30"/></li>
        <li><img src="data2/images/p1000223.jpg" alt="P1000223" title="P1000223" id="wows2_31"/></li>
        <li><img src="data2/images/p1000224.jpg" alt="P1000224" title="P1000224" id="wows2_32"/></li>
        <li><img src="data2/images/p1000225.jpg" alt="P1000225" title="P1000225" id="wows2_33"/></li>
        <li><img src="data2/images/p1000226.jpg" alt="P1000226" title="P1000226" id="wows2_34"/></li>
        <li><img src="data2/images/p1000227.jpg" alt="P1000227" title="P1000227" id="wows2_35"/></li>
        <li><img src="data2/images/p1000228.jpg" alt="P1000228" title="P1000228" id="wows2_36"/></li>
        <li><img src="data2/images/p1000229.jpg" alt="P1000229" title="P1000229" id="wows2_37"/></li>
        <li><img src="data2/images/p1000230.jpg" alt="P1000230" title="P1000230" id="wows2_38"/></li>
        <li><img src="data2/images/p1000231.jpg" alt="P1000231" title="P1000231" id="wows2_39"/></li>
        <li><img src="data2/images/p1000232.jpg" alt="P1000232" title="P1000232" id="wows2_40"/></li>
        <li><img src="data2/images/p1000233.jpg" alt="P1000233" title="P1000233" id="wows2_41"/></li>
        <li><img src="data2/images/p1000234.jpg" alt="P1000234" title="P1000234" id="wows2_42"/></li>
        <li><a href="http://wowslider.com"><img src="data2/images/p1000235.jpg" alt="wowslider" title="wowslider" id="wows2_43"/></a></li>
        <li><img src="data2/images/p1000236.jpg" alt="P1000236" title="P1000236" id="wows2_44"/></li>
    </ul></div>
<span class="wsl"><a href="http://wowslider.com/vs">jquery slideshow</a> by WOWSlider.com v7.4m</span>
    <div class="ws_shadow"></div>
    </div>  
    <script type="text/javascript" src="engine2/wowslider.js"></script>
    <script type="text/javascript" src="engine2/script.js"></script>
                <!-- end of middle slider -->

            </div>
            <h2 class="text-center">Social</h2>
            <p> All the texts and I'm typing and words and this needs to be really long. And pop culture references. Meta! Meta! Companies. Yelp is Cool. So is Microsoft and Amazon. One of who Yelp makes an app for and one of who makes an app for Yelp. Guesses anyone?</p>
        </div>

        <div class="col-lg-4">
            <div class="asset_box"></div>
            <h2 class="text-center">Service</h2>
            <p> All the texts and I'm typing and words and this needs to be really long. And pop culture references. Meta! Meta! Companies. Yelp is Cool. So is Microsoft and Amazon. One of who Yelp makes an app for and one of who makes an app for Yelp. Guesses anyone?</p>
        </div>
    </div>
</div>
<!-- End 3 Blocks -->

<!-- Sponsor Block -->
<div class="container-fluid" id="index_container">
    <h2 class="text-center"> Sponsors </h2>
    <p> There will be some soon. </p>

</div>
{% endblock %}
