{% extends "layout.phtml" %}

{% block title %}
CSE Scholars
{% endblock %}

{% block page_title %}
University of Michigan
{% endblock %}

{% block content %}


<!-- Carousel or main image or whatever -->
<div class="container_top container-fluid" id="index_container">
    <div class="row asset_top">
    </div>
</div>
<!-- End the thing -->

<!-- 3 Blocks -->
<div class="container-fluid" id="index_container">
    <div class="row">
        <div class="col-lg-4">
            <div class="asset_box"></div>
            <h2 class="text-center">Corporate</h2>
            <p> All the texts and I'm typing and words and this needs to be really long. And pop culture references. Meta! Meta! Companies. Yelp is Cool. So is Microsoft and Amazon. One of who Yelp makes an app for and one of who makes an app for Yelp. Guesses anyone?</p>
        </div>

        <div class="col-lg-4">
            <div class="asset_box"></div>
            <h2 class="text-center">Social</h2>
            <p> All the texts and I'm typing and words and this needs to be really long. And pop culture references. Meta! Meta! Companies. Yelp is Cool. So is Microsoft and Amazon. One of who Yelp makes an app for and one of who makes an app for Yelp. Guesses anyone?</p>
        </div>

        <div class="col-lg-4">
            <div class="asset_box"></div>
            <h2 class="text-center">Service</h2>
            <p> All the texts and I'm typing and words and this needs to be really long. And pop culture references. Meta! Meta! Companies. Yelp is Cool. So is Microsoft and Amazon. One of who Yelp makes an app for and one of who makes an app for Yelp. Guesses anyone?</p>
        </div>
    </div>
</div>
<!-- End 3 Blocks -->

<!-- Sponsor Block -->
<div class="container-fluid" id="index_container">
    <h2 class="text-center"> Sponsors </h2>
    <p> There will be some soon. </p>

</div>
{% endblock %}
