<!-- Layout file -->
<!DOCTYPE html>
<html>
    <head>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Bootstrap -->

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

        <!-- Font Awesome -->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

        
        <link href="/static/css/style.css" rel="stylesheet">
        <link href="/static/css/reset.css" rel="stylesheet">
        {% block js %}
        {% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <!-- Navigation Bar -->
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="/index.php">Home</a></li>
                <li><a href="/calendar.php">Calendar</a></li>
                <li><a href="/officers.php">Officers</a></li>
                <li><a href="/views/resume_book.php">Resume Book</a></li>
                {% if login == "Prospective" or login == "Member" or login == "Admin" %}
                    <li><a href="/views/member_info.php">My Profile</a></li>
                    <li><a href="/login/logout.php">Logout</a></li>
                {% else %}
                    <li><a href="/login/index.php">Login</a></li>
                {% endif %}
                {% if login == "Admin" %}
                    <li><a href="/views/admin_page.php">Admin Page</a></li>
                {% endif %}
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>

        <!-- Logo Block -->
        <div class="container">
            <img src="/static/images/logo.png" class="row text-center center-block img-responsive" id="logo" s/>
            <h1 class="row text-center center-block">CSE Scholars</h1>
            <h2 class="row text-center center-block">{% block page_title %}{% endblock %}</h2>
        </div>
        <!-- End logo block -->
        {% block content %}{% endblock %}
        {% block endjs %}{% endblock %}

    <!-- Footer -->
    <div class="container-fluid footer" id="index_container">
        <div class="row">
            <div class="col-lg-2">
                <p>CSE Scholars</p>
                <p>University of Michigan</p>
            </div>
            <div class="col-lg-3 col-lg-offset-7">
                <ul>
                    <li><a href="https://www.facebook.com/pages/CSE-Scholars/238284829559154"><img src="/static/images/facebook.png"></a>
                    <li><img src="/static/images/twitter.png"></li>
                    <li><img src="/static/images/linkedin.png"></li>
                <ul>
            </div>
        </div>
    </div>
    </body>
</html>
