{% extends "layout.phtml" %}

{% block title %}
Member Info - {{member.name}}
{% endblock %}

{% block page_title %}
My Information
{% endblock %}

{% block js %}
<script src="/static/js/Chart.min.js"></script>
{% endblock %}

{% block endjs %}
<script type="text/javascript">
var options = {};
var data = {
  labels: ["Corporate", "Service", "Social"],
  datasets: [
    {
      label: "Needed for membership",
      fillColor: "rgba(220,220,220,0.2)",
      strokeColor: "rgba(220,220,220,1)",
      pointColor: "rgba(220,220,220,1)",
      pointStrokeColor: "#fff",
      pointHighlightFill: "#fff",
      pointHighlightStroke: "rgba(220,220,220,1)",
      data: [3,5,3]
    },
    {
      label: "What you have",
      fillColor: "rgba(151,187,205,0.2)",
      strokeColor: "rgba(151,187,205,1)",
      pointColor: "rgba(151,187,205,1)",
      pointStrokeColor: "#fff",
      pointHighlightFill: "#fff",
      pointHighlightStroke: "rgba(151,187,205,1)",
      data: [{{member.corporate}}, {{member.service}}, {{member.social}}]
    }
  ]
};

var ctx = document.getElementById("memberChart").getContext("2d");
var myRadarChart = new Chart(ctx).Radar(data, options);
</script>
{% endblock %}

{% block content %}
        <!-- Display member info -->
        <div class="container-fluid">
            <div class="row">
              <div class="col-lg-6">
                <canvas id="memberChart" width="400" height="400"></canvas>
              </div>

              <div class="col-lg-6">
                <form class="form-horizontal" role="form" name="input" action="{{ROOTPATH}}/views/update_user.php" method="post">
                  <div class="form-group">
                    <label for="namebox">Name:</label>
                    <input class="form-control" id="namebox" type="text" name="name" value="{{ member.name }}">
                  </div>
                  <div class="form-group">
                    <label for="majorbox">Major:</label>
                    <input class="form-control" id="majorbox" type="text" name="major" value="{{ member.major }}">
                  </div>
                  <div class="form-group">
                    <label for="monthbox">Grad Month:</label>
                    <select class="form-control" id="monthbox" name="month" value="{{ member.gradMonth }}">
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                      <option>4</option>
                      <option>5</option>
                      <option>6</option>
                      <option>7</option>
                      <option>8</option>
                      <option>9</option>
                      <option>10</option>
                      <option>11</option>
                      <option>12</option>
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="yearbox">Grad Year:</label>
                    <select class="form-control" id="yearbox" name="year" value="{{ member.gradYear }}">
                      <option>2015</option>
                      <option>2016</option>
                      <option>2017</option>
                      <option>2018</option>
                      <option>2019</option>
                      <option>2020</option>
                      <option>2021</option>
                    </select>
                  </div>
                  <button type="submit" class="btn btn-default"><i class="fa fa-paper-plane" id="button"></i>Submit</button>
                </form>

                <!-- Form for uploading resume -->
                {% if member.type == 'Member' %}
                <form class="form-horizontal" action="{{ROOTPATH}}/views/upload_resume.php" method="post"
                enctype="multipart/form-data">
                  <div class="form-group">
                    <label for="file">Filename:</label>
                    <input type="file" name="file" id="file">
                  </div>
                  <button type="submit" class="btn btn-default"><i class="fa fa-paper-plane" id="button"></i>Submit</button>
                </form>
                {% endif %}
              </div>
            </div>

            <div class="row">
              <h2>Benefits of Membership</h2>
              <p>Words will be here.</p>
            </div>
        </div>

{% endblock %}
