{% extends "layout.phtml" %}

{% block title %}
CSE Scholars - Officers
{% endblock %}

{% block page_title %}
Officers
{% endblock %}

{% block content %}
<div class="container-fluid" id="index_container">
    <!-- One row per 2 officers -->
    <div class="row officer_row">
        <!-- Begin president -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/president.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>President</h3>
            <h4>Preeti Mohan</h4>
            <p>P, one step above VP</p>
        </div>

        <!-- Begin VP -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/vice_president.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Vice President</h3>
            <h4>Patrick Korth</h4>
            <p> VP, not much more to say</p>
        </div>
    </div>

    <div class="row officer_row">
        <!-- Corp Chair -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/corporate_chair.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Corporate Chair</h3>
            <h4>Alex Stephen</h4>
            <p>Talks to the bosses</p>
        </div>

        <!-- Begin Secretary -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/secretary.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Secretary</h3>
            <h4>Andrea Gines</h4>
            <p> She cool, real cool</p>
        </div>
    </div>

    <div class="row officer_row">
        <!-- Begin market chair  -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/marketing_chair.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Marketing Chair</h3>
            <h4>Alex Levine</h4>
            <p>Marketing, he puts us out there</p>
        </div>


        <!-- Begin SC -->

        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/social_chair.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Social Chair</h3>
            <h4>Brandon Waggoner</h4>
            <p>Social chair, talks a lot</p>
        </div>
    </div>

    <div class="row officer_row">
        <!-- Corp Chair -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/community_service.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Community Service</h3>
            <h4>Mo Hussein</h4>
            <p>Helps the community, we like him</p>
        </div>

        <!-- Begin Web -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/webmaster.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Webmaster</h3>
            <h4>Taku Rusike</h4>
            <p>Best for last</p>
        </div>

    </div>

</div>
{% endblock %}
