{% extends "layout.phtml" %}

{% block title %}
CSE Scholars - Officers
{% endblock %}

{% block page_title %}
Officers
{% endblock %}

{% block content %}
<div class="container-fluid" id="index_container">
    <!-- One row per 2 officers -->
    <div class="row officer_row">
        <!-- Begin president -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/president.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>President</h3>
            <h4>Patrick Korth</h4>
            <p>Patrick deserves far more in life than boilerplate text. Too bad that's all he's getting right now.</p>
        </div>

        <!-- Begin VP -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/president.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Vice President</h3>
            <h4>Addison</h4>
            <p>Addison also deserves more in life than boilerplate. Especially a last name. But, I'm quite lazy. I'm sorry Addison.</p>
        </div>
    </div>

    <div class="row officer_row">
        <!-- Begin president -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/president.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>President</h3>
            <h4>Patrick Korth</h4>
            <p>Patrick deserves far more in life than boilerplate text. Too bad that's all he's getting right now.</p>
        </div>

        <!-- Begin VP -->
        <div class="col-lg-2 officer_pic">
            <img src="/static/images/officers/president.jpg" class="img-circle">
        </div>
        <div class="col-lg-4">
            <h3>Vice President</h3>
            <h4>Addison</h4>
            <p>Addison also deserves more in life than boilerplate. Especially a last name. But, I'm quite lazy. I'm sorry Addison.</p>
        </div>
    </div>

</div>
{% endblock %}
