{% extends "layout.phtml" %}

{% block title %}
Resume Book
{% endblock %}

{% block page_title %}
Resume Book
{% endblock %}

{% block content %}
<div class="container-fluid" id="index_container">
        <table class="table">
                <th>Name</th>
                <th>Email</th>
                <th>Major</th>
                <th>Graduation</th>
                <th>Resume</th>
                <th>Events Attended</th>
                <th>Service Hours</th>

        {% for userData in members %}
        <tr>
            <td>{{userData.name}}</td>
            <td>{{userData.uniqname}}@umich.edu</td>
            <td>{{userData.major}}</td>
            <td>{{userData.gradMonth}}/{{userData.gradYear}}</td>
            <td><a href="{{userData.resume.url}}">Resume</a></td>
            <td style=\"text-align:center;\">{{userData.events}}</td>
            <td style=\"text-align:center;\">{{userData.serviceHours}}</td>
        </tr>
        {% endfor %}
        </table>
</div>
{% endblock %}
